### ISSUE TITLE
Exception in Help -> Repository

### ISSUE THREAD

**Issue by klofi** [jlord/git-it-electron#151]
Git-it-Win-ia32.zip **version 4.2.0**

1. Open: Help -> Repository
2. Observe error

![git-it-electron-error](https://cloud.githubusercontent.com/assets/1025624/17924186/e67bba22-69e7-11e6-8f98-19cc5e8ffb6d.png)

**Comment by andela-cmutembei** [comment]
I also get the same error on OS X 10.11.6 running version 1.2.6. Here is a screenshot.


<img width="984" alt="screen shot 2016-09-05 at 14 44 51" src="https://cloud.githubusercontent.com/assets/10899666/18252426/086a91b8-7397-11e6-8c10-5fff09623351.png">

Seems to be as a result of a missing depedency.

**Comment by jlord** [comment]
I've added a new version that should fix this, here: https://github.com/jlord/git-it-electron/releases/tag/4.2.2 🍍

**Comment by collinmutembei** [comment]
Issue persists on `v4.2.2` on Mac OS X 10.12

<img width="1680" alt="screen shot 2016-10-16 at 10 36 05" src="https://cloud.githubusercontent.com/assets/10899666/19416069/5b75c4b4-938f-11e6-9c98-1995ae818003.png">

Submitting fix in a jiffy 😺
